# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  python_3.6:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps: &steps
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: python linting
          command: |
            . venv/bin/activate
            pip install flake8
            flake8 .

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install coverage
            coverage run --source ./async_signalr_client -m pytest ./tests/unit --html=./test-reports/result.html --junitxml test-reports/junit.xml
            coverage report
            coverage html -d ./test-reports/coverage

      - store_artifacts:
          path: test-reports
          destination: test-reports

  python_3.7:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo
    steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - python_3.6
      - python_3.7